<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>irden.space</groupId>
    <artifactId>plugins</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <properties>

    </properties>

    <profiles>
        <profile>
            <id>dev</id>
            <dependencies>
                <dependency>
                    <groupId>irden.space.plugin</groupId>
                    <artifactId>plugin-player-manager</artifactId>
                    <version>1.0.0</version>
                </dependency>
                <dependency>
                    <groupId>irden.space.plugin</groupId>
                    <artifactId>plugin-command-handler</artifactId>
                    <version>1.0.0</version>
                </dependency>
                <dependency>
                    <groupId>irden.space.plugin</groupId>
                    <artifactId>plugin-discord-bot</artifactId>
                    <version>1.0.0</version>
                </dependency>
                <dependency>
                    <groupId>irden.space.plugin</groupId>
                    <artifactId>plugin-star-custom-chat</artifactId>
                    <version>1.0.0</version>
                </dependency>
                <dependency>
                    <groupId>irden.space.plugin</groupId>
                    <artifactId>plugin-runtime-admin</artifactId>
                    <version>1.0.0</version>
                </dependency>
                <dependency>
                    <groupId>irden.space.plugin</groupId>
                    <artifactId>plugin-ban-manager</artifactId>
                    <version>1.0.0</version>
                </dependency>
                <dependency>
                    <groupId>irden.space.plugin</groupId>
                    <artifactId>plugin-general</artifactId>
                    <version>1.0.0</version>
                </dependency>
                <dependency>
                    <groupId>irden.space.plugin</groupId>
                    <artifactId>plugin-native-server-lifespan</artifactId>
                    <version>1.0.0</version>
                </dependency>
                <dependency>
                    <groupId>irden.space.plugin</groupId>
                    <artifactId>plugin-planet-backup</artifactId>
                    <version>1.0.0</version>
                </dependency>
                <dependency>
                    <groupId>irden.space.plugin</groupId>
                    <artifactId>plugin-launcher</artifactId>
                    <version>1.0.0</version>
                </dependency>
                <dependency>
                    <groupId>irden.space.plugin</groupId>
                    <artifactId>plugin-irden</artifactId>
                    <version>1.0.0</version>
                </dependency>
                <dependency>
                    <groupId>irden.space.plugin</groupId>
                    <artifactId>plugin-planet-protect</artifactId>
                    <version>1.0.0</version>
                </dependency>
                <dependency>
                    <groupId>irden.space.plugin</groupId>
                    <artifactId>plugin-osb-detector</artifactId>
                    <version>1.0.0</version>
                </dependency>
            </dependencies>
        </profile>
    </profiles>
    <modules>
        <module>plugin-command-handler</module>
        <module>plugin-player-manager</module>
        <module>plugin-discord-bot</module>
        <module>plugin-star-custom-chat</module>
        <module>plugin-runtime-admin</module>
        <module>plugin-ban-manager</module>
        <module>plugin-general</module>
        <module>plugin-native-server-lifespan</module>
        <module>plugin-planet-backup</module>
        <module>plugin-launcher</module>
        <module>plugin-irden</module>
        <module>plugin-planet-protect</module>
        <module>plugin-osb-detector</module>
    </modules>

</project>
