spring:
  application:
    name: irden-proxy

proxy:
  listen-host: 0.0.0.0
  listen-port: 7777
  upstream-host: irden.space
  upstream-port: 21024

assets:
  store:
    enabled: true
    archives:
      - D:/Steam/steamapps/common/Starbound/assets/packed.pak
    excluded-extensions:
      - .ogg
      - .png
      - .wav

logging:
  level:
    root: INFO
    irden.space.proxy.application: INFO
